jaxon_ajax:
    app:
      namespace:                      "\\Jaxon\\App"

    lib:
      core:
        language:                      "en"
        encoding:                      "UTF-8"
        request:
          uri:                         "/exp/symfony/jaxon"
        prefix:
          class:                       ""
        debug:
          on:                          false
          verbose:                     false
        error:
          handle:                      false

      js:
          lib:
          app:
          extern:                      false
          minify:                      false

      dialogs:
          libraries:
                                       - pgwjs
          default:
              modal:                   bootstrap
              alert:                   toastr
          toastr:
              options:
                closeButton:           true
                positionClass:         "toast-top-center"

          pgwjs:
              modal:
                  options:
                      closeOnEscape:             true
                      closeOnBackgroundClick:    true
                      maxWidth:                  600
