jaxon_ajax:
    app:
      namespace:                      "\\Jaxon\\App"

    lib:
      core:
        language:                      "en"
        encoding:                      "UTF-8"
        request:
          uri:                         "/exp/symfony/jaxon"
        prefix:
          class:                       ""
        debug:
          on:                          false
          verbose:                     false
        error:
          handle:                      false

      js:
          lib:
          app:
          extern:                      false
          minify:                      false

      dialogs:
          default:
              modal:                       pgwjs
              alert:                       toastr
          toastr:
              options:
                closeButton:                 true
                closeMethod:                 "fadeOut"
                closeDuration:               300
                closeEasing:                 "swing"
                positionClass:               "toast-top-center"

          pgwjs:
              modal:
                  options:
                      closeOnEscape:             true
                      closeOnBackgroundClick:    true
                      maxWidth:                  600
