jaxon:
  core:
    debug:
      on:                          true
    prefix:
      class:                       "Jaxon"
    request:
      csrf_meta:                   "csrf-token"
  
  dialogs:
    default:
      modal:                       pgwjs
      alert:                       toastr
    pgwjs:
      assets:
        include:                   true
      modal:
        options:
          closeOnEscape:           true
          closeOnBackgroundClick:  true
          maxWidth:                600
    toastr:
      options:
        closeButton:               true
        closeMethod:               "fadeOut"
        closeDuration:             300
        closeEasing:               "swing"
        positionClass:             "toast-top-center"
          