jaxon:
  core:
    debug:
      on:                          true
    prefix:
      class:                       "Jaxon"
    request:
      csrf_meta:                   "csrf-token"

  toastr:
    options:
      closeButton:                 true
      closeMethod:                 "fadeOut"
      closeDuration:               300
      closeEasing:                 "swing"
      positionClass:               "toast-bottom-right"
  
  dialogs:
    libraries:
      modal:                       bootstrap
      alert:                       toastr
    pgw:
      assets:
        include:                   true
      modal:
        options:
          closeOnEscape:           true
          closeOnBackgroundClick:  true
          maxWidth:                600
    toastr:
      options:
        closeButton:               true
        positionClass:             "toast-top-center"
          